project_name: service

archives:
  - id: service
    builds:
      - client
      - server
    files:
      - LICENSE
    format: tar.gz
    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"

brews:
  - name: service
    caveats: An example of the goreleaser usage.
    commit_author:
      name: Kamil Samigullin
      email: kamil@samigullin.info
    description: Template for a typical service written on Go.
    folder: Formula
    homepage: https://go-service.octolab.org/
    repository:
      owner: octolab
      name: homebrew-tap
    install: |
      bin.install "service"

      output = Utils.popen_read("#{bin}/server completion bash")
      (bash_completion/"server").write output

      output = Utils.popen_read("#{bin}/server completion fish")
      (fish_completion/"server.fish").write output

      output = Utils.popen_read("#{bin}/server completion zsh")
      (zsh_completion/"_server").write output

      bin.install "client"

      output = Utils.popen_read("#{bin}/client completion bash")
      (bash_completion/"client").write output

      output = Utils.popen_read("#{bin}/client completion fish")
      (fish_completion/"client.fish").write output

      output = Utils.popen_read("#{bin}/client completion zsh")
      (zsh_completion/"_client").write output

      prefix.install_metafiles
    test: |
      system "#{bin}/server version"
      system "#{bin}/client version"

builds:
  - id: client
    binary: client
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - linux
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    main: ./cmd/client
  - id: server
    binary: server
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - linux
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    main: ./cmd/server

checksum: { name_template: checksums.txt }

release:
  github:
    owner: octomation
    name: go-service
