### API

POST {{service-api-host}}/twirp/api.service.v1.GreeterService/Hello
Content-Type: application/json

{
  "subject": "World"
}

###

POST {{service-api-host}}/twirp/api.service.v1.GreeterService/Sign
Content-Type: application/json

{}

###

GRPC {{service-api-host}}/api.service.v1.GreeterService/Hello

{
  "subject": "World"
}

###

GRPC {{service-api-host}}/api.service.v1.GreeterService/Sign

### Debug

GET {{service-debug-host}}/debug/pprof/
