### API

POST {{service-gateway}}/v1/hello
Content-Type: application/json

{
  "subject": "World"
}

###

GET {{service-gateway}}/v1/sign

###

GRPC {{service-grpc-host}}/api.rpc.v1.GreeterService/Hello

{
  "subject": "World"
}

###

GRPC {{service-grpc-host}}/api.rpc.v1.GreeterService/Sign

###

POST {{service-twirp-host}}/twirp/api.rpc.v1.GreeterService/Hello
Content-Type: application/json

{
  "subject": "World"
}

###

POST {{service-twirp-host}}/twirp/api.rpc.v1.GreeterService/Sign
Content-Type: application/json

{}

### Profiler

GET {{service-profile-host}}/debug/pprof/
