name: publishing

on:
  push:
    tags: [ '*' ]

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with: { fetch-depth: 0 }
      - uses: actions/setup-go@v3
        with: { go-version: '1.18' }
      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            %LocalAppData%\go-build
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: ${{ runner.os }}-go-
      - run: make env deps-fetch test
      - uses: goreleaser/goreleaser-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_TOKEN }}
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist

  notify:
    needs: [ test ]
    if: ${{ failure() || success() }}
    runs-on: ubuntu-18.04

    steps:
      - uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ needs.test.result }}
          SLACK_ICON: https://github.com/github.png?size=64
          SLACK_TITLE: '${{ github.repository }}: ${{ github.workflow }}'
          SLACK_USERNAME: GitHub Actions
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
